### ISSUE TITLE
Merge lanes

### ISSUE THREAD

**Issue by MiraHu** [AIPSE/AIPSELib#11]
Lanes should be merged so that we only have 1 volume per link (the sum of lane-wise volumes, regardless of direction)

**Comment by LachlanBirdsey** [comment]
Two approaches to this:

1. We find the link duplicates and merge volume information on the fly
2. Link and volume merging is done in the `shutdown` phase of the simulation

1 is less expensive, harder to implement, we lose the finer levels of data. 2 is more expensive (possible painfully so), is easier to implement, we can more easily fine tune the levels of data we need.

**Comment by MiraHu** [comment]
I vote for 2. (Although wondering what "painfully expensive" means..)

**Comment by LachlanBirdsey** [comment]
@MiraHu turns out you get your wish. There's significant change that would have to happen to make 1 work well.

"painfully expensive" refers to the time. In it's easiest implementation its a complexity of O(n^2) while in a nice one it should be O(nlogn). We will see what happens.

**Comment by LachlanBirdsey** [comment]
Merging is complete except for motorways since OSM stores motorways and trunks as separate oneway roads. This merging can be done with a heuristic approach. Will explore later when needed. This is effectively closed.
